import { useState } from 'react'
import { BarChart3, Cloud, Database, FileText, LockKeyhole, Mail, Rocket, Server, ShieldCheck } from 'lucide-react'
import { Link } from 'react-router-dom'

const plans = [
  { id: 'startup', eyebrow: 'Combo 01', title: 'Landing & Startup', audience: 'Para profesionales y PyMEs que necesitan captar clientes desde el primer día.', icon: Rocket, features: [{ icon: Rocket, text: 'Landing ultra rápida en React / Vite' }, { icon: ShieldCheck, text: 'Hosting privado, dominio y SSL por 1 año' }, { icon: Mail, text: 'Formulario EmailJS / SMTP dedicado' }, { icon: BarChart3, text: 'Mobile, SEO técnico y métricas básicas' }] },
  { id: 'business', eyebrow: 'Más elegido', title: 'Business & Scaling', audience: 'Para empresas que gestionan clientes, ventas y transacciones.', icon: Server, featured: true, features: [{ icon: Server, text: 'Web corporativa o e-commerce escalable' }, { icon: Database, text: 'Base de datos privada integrada' }, { icon: FileText, text: 'Facturación o pagos MercadoPago / Stripe' }, { icon: Cloud, text: 'Cloud dedicado, backups y dashboard' }] },
  { id: 'enterprise', eyebrow: 'Combo 03', title: 'Enterprise / Custom Engine', audience: 'Para SaaS, plataformas complejas y sistemas a medida.', icon: LockKeyhole, features: [{ icon: Rocket, text: 'Microservicios, APIs REST y arquitectura a medida' }, { icon: LockKeyhole, text: 'Autenticación JWT / OAuth2 segura' }, { icon: FileText, text: 'Integración contable y reportes en tiempo real' }, { icon: Cloud, text: 'Cloud privado, autoescalado y soporte prioritario' }] },
]

export function PricingCards() {
  const [mode, setMode] = useState<'single' | 'maintenance'>('single')
  return <section className="pricing-section mx-auto max-w-7xl px-4 pb-28 sm:px-6" aria-labelledby="pricing-title"><div className="pricing-head"><div><p className="eyebrow">Soluciones llave en mano</p><h2 id="pricing-title" className="section-title mt-4">Un producto completo. <span className="gradient-text">Una operación clara.</span></h2><p>Elegí un punto de partida y lo ajustamos a tu operación, integración contable y nivel de soporte.</p></div><div className="pricing-toggle" aria-label="Modalidad de contratación"><button type="button" className={mode === 'single' ? 'pricing-toggle-active' : ''} onClick={() => setMode('single')} aria-pressed={mode === 'single'}>Pago único</button><button type="button" className={mode === 'maintenance' ? 'pricing-toggle-active' : ''} onClick={() => setMode('maintenance')} aria-pressed={mode === 'maintenance'}>Mantenimiento mensual <span>Ahorra 20%</span></button></div></div><div className="pricing-grid">{plans.map((plan) => { const PlanIcon = plan.icon; return <article key={plan.id} className={`pricing-card ${plan.featured ? 'pricing-card-featured' : ''}`}><div className="pricing-card-top"><div className="pricing-plan-icon"><PlanIcon size={23} /></div><span>{plan.eyebrow}</span></div><h3>{plan.title}</h3><p className="pricing-audience">{plan.audience}</p><div className="pricing-divider" /><ul>{plan.features.map(({ icon: Icon, text }) => <li key={text}><Icon size={16} />{text}</li>)}</ul><div className="pricing-card-foot"><p>{mode === 'single' ? 'Implementación completa, alcance definido y entrega documentada.' : 'Operación continua, monitoreo, mejoras y soporte según SLA.'}</p><Link to="/contacto" className="button-primary">Solicitar propuesta</Link></div></article>})}</div></section>
}
